# WhatATheme
markdown: kramdown

# URL of the Site
url: 'need.medicinals.me'
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Vida Sol
# Description of the Site
description: Ancient Truths
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://raw.githubusercontent.com/r00t-101-LoL/WhatATheme/master/assets/images/golden.webp
# https://res.cloudinary.com/need-medicinals-me/image/upload/b_rgb:060000,bo_100px_solid_rgb:000,co_rgb:000000,dpr_auto,e_sharpen:2000,f_auto,g_center,z_0.1/v1613688495/golden.png
# https://res.cloudinary.com/need-medicinals-me/image/upload/b_rgb:060000,co_rgb:000000,dpr_auto,e_sharpen:100,f_auto,z_0.1/v1613688495/golden.png 
# https://res.cloudinary.com/need-medicinals-me/image/upload/b_rgb:060000,co_rgb:000000,dpr_auto,e_sharpen:100,f_auto,z_0.1/v1613688495/golden.png
# https://res.cloudinary.com/need-medicinals-me/image/upload/w_1000,ar_16:9,c_fill,g_auto,e_sharpen/v1613688495/golden.png 
# https://res.cloudinary.com/need-medicinals-me/image/upload/v1613688495/golden.png
# https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: delta-won@protonmail.com
facebook_username: sollotus
twitter_username: sollotus
instagram_username: sollotus
linkedin_username: sollotus
github_username:  sollotus
youtube_channel_id: 
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /

# Google Analytics
google-analytics: 

# Disqus
disqus-shortname: sollotus

# Name of the Author
author-name: Illusion
# URL for the Image of the Author
author-image: https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png
# 60 Words About the Author
author-about: Ex quo consequitur personam individuam nullo modo reduci posse illis omnibus quae ipsam comprimere et ad nihil redigere valerent intra saepta anonyma consortionis, institutionis, structurae, systematis.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/r00t-101-LoL

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
